  name: ShopGUI
  main: angga7togk.shopgui.ShopGUI
  version: 1.0.0
  api: 1.0.0
  author: Angga7Togk
  description: "ShopGUI by angga7togk"
  depend:
    - FormAPI
    - FakeInventories
    - EconomyAPI
  website: "https://7togksmp.com"

  permissions:
    shop.command:
      default: true
    shop.edit:
      default: op